id: PCCFB29AE
initial_creation_type: ocr
source_metadata:
  volumes:
    d311ea7e32b642239c0420fbdef41f4f:
      base_file: v056.txt
      image_group_id: I1PD95901
      title: འཕགས་པ་ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པ་བདུན་བརྒྱ་པ་རྒྱ་ཆེར་བཤད་པ།
      total_pages: 1682
      volume_number: 56
